// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NamR
{
    static class Vsix
    {
        public const string Id = "A98A9358-9F24-4407-AAB7-5871243606AA";
        public const string Name = "NamR";
        public const string Description = "This extension will provide the IntelliSense completion for naming things in C#. That's right - no more typing cancellationToken in a parameter declaration!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ralf 'bexxx' Beckers";
        public const string Tags = "IntelliSense, naming, name, c#";
    }
}
